# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

builds:
  - binary: pulumi-resource-mid
    main: ./provider/cmd/pulumi-resource-mid/
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      # The line below MUST align with the module in current provider/go.mod
      - -X github.com/sapslaj/pulumi-mid/provider/Version={{.Tag }}

archives:
  - id: archive
    name_template: '{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}'

changelog:
  disable: true

release:
  disable: false
