[project]
name = "mid"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "deepmerge>=2.0",
  "jinja2>=3.1.0",
  "pyyaml>=5.1",
]
