# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins
from . import _utilities
import typing

# Export this package's modules as members:
from .provider import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_mid.agent as __agent

    agent = __agent
    import pulumi_mid.config as __config

    config = __config
    import pulumi_mid.resource as __resource

    resource = __resource
else:
    agent = _utilities.lazy_import("pulumi_mid.agent")
    config = _utilities.lazy_import("pulumi_mid.config")
    resource = _utilities.lazy_import("pulumi_mid.resource")

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "mid",
  "mod": "resource",
  "fqn": "pulumi_mid.resource",
  "classes": {
   "mid:resource:AnsibleTaskList": "AnsibleTaskList",
   "mid:resource:Apt": "Apt",
   "mid:resource:Exec": "Exec",
   "mid:resource:File": "File",
   "mid:resource:FileLine": "FileLine",
   "mid:resource:Group": "Group",
   "mid:resource:Package": "Package",
   "mid:resource:Service": "Service",
   "mid:resource:SystemdService": "SystemdService",
   "mid:resource:User": "User"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "mid",
  "token": "pulumi:providers:mid",
  "fqn": "pulumi_mid",
  "class": "Provider"
 }
]
""",
)
