// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

export class Exec extends pulumi.CustomResource {
  /**
   * Get an existing Exec resource's state with the given name, ID, and optional extra
   * properties used to qualify the lookup.
   *
   * @param name The _unique_ name of the resulting resource.
   * @param id The _unique_ provider ID of the resource to lookup.
   * @param opts Optional settings to control the behavior of the CustomResource.
   */
  public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Exec {
    return new Exec(name, undefined as any, { ...opts, id: id });
  }

  /** @internal */
  public static readonly __pulumiType = "mid:resource:Exec";

  /**
   * Returns true if the given object is an instance of Exec.  This is designed to work even
   * when multiple copies of the Pulumi SDK have been loaded into the same process.
   */
  public static isInstance(obj: any): obj is Exec {
    if (obj === undefined || obj === null) {
      return false;
    }
    return obj["__pulumiType"] === Exec.__pulumiType;
  }

  public readonly config!: pulumi.Output<outputs.ResourceConfig | undefined>;
  public readonly connection!: pulumi.Output<outputs.Connection | undefined>;
  public readonly create!: pulumi.Output<outputs.ExecCommand>;
  public readonly delete!: pulumi.Output<outputs.ExecCommand | undefined>;
  public readonly deleteBeforeReplace!: pulumi.Output<boolean | undefined>;
  public readonly dir!: pulumi.Output<string | undefined>;
  public readonly environment!: pulumi.Output<{ [key: string]: string } | undefined>;
  public readonly expandArgumentVars!: pulumi.Output<boolean | undefined>;
  public readonly logging!: pulumi.Output<string | undefined>;
  public readonly /*out*/ stderr!: pulumi.Output<string>;
  public readonly /*out*/ stdout!: pulumi.Output<string>;
  public readonly triggers!: pulumi.Output<outputs.TriggersOutput>;
  public readonly update!: pulumi.Output<outputs.ExecCommand | undefined>;

  /**
   * Create a Exec resource with the given unique name, arguments, and options.
   *
   * @param name The _unique_ name of the resource.
   * @param args The arguments to use to populate this resource's properties.
   * @param opts A bag of options that control this resource's behavior.
   */
  constructor(name: string, args: ExecArgs, opts?: pulumi.CustomResourceOptions) {
    let resourceInputs: pulumi.Inputs = {};
    opts = opts || {};
    if (!opts.id) {
      if (args?.create === undefined && !opts.urn) {
        throw new Error("Missing required property 'create'");
      }
      resourceInputs["config"] = args?.config;
      resourceInputs["connection"] = args
        ? (args.connection ? pulumi.output(args.connection).apply(inputs.connectionArgsProvideDefaults) : undefined)
        : undefined;
      resourceInputs["create"] = args?.create;
      resourceInputs["delete"] = args?.delete;
      resourceInputs["deleteBeforeReplace"] = args?.deleteBeforeReplace;
      resourceInputs["dir"] = args?.dir;
      resourceInputs["environment"] = args?.environment;
      resourceInputs["expandArgumentVars"] = args?.expandArgumentVars;
      resourceInputs["logging"] = args?.logging;
      resourceInputs["triggers"] = args?.triggers;
      resourceInputs["update"] = args?.update;
      resourceInputs["stderr"] = undefined /*out*/;
      resourceInputs["stdout"] = undefined /*out*/;
    } else {
      resourceInputs["config"] = undefined /*out*/;
      resourceInputs["connection"] = undefined /*out*/;
      resourceInputs["create"] = undefined /*out*/;
      resourceInputs["delete"] = undefined /*out*/;
      resourceInputs["deleteBeforeReplace"] = undefined /*out*/;
      resourceInputs["dir"] = undefined /*out*/;
      resourceInputs["environment"] = undefined /*out*/;
      resourceInputs["expandArgumentVars"] = undefined /*out*/;
      resourceInputs["logging"] = undefined /*out*/;
      resourceInputs["stderr"] = undefined /*out*/;
      resourceInputs["stdout"] = undefined /*out*/;
      resourceInputs["triggers"] = undefined /*out*/;
      resourceInputs["update"] = undefined /*out*/;
    }
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    super(Exec.__pulumiType, name, resourceInputs, opts);
  }
}

/**
 * The set of arguments for constructing a Exec resource.
 */
export interface ExecArgs {
  config?: pulumi.Input<inputs.ResourceConfigArgs>;
  connection?: pulumi.Input<inputs.ConnectionArgs>;
  create: pulumi.Input<inputs.ExecCommandArgs>;
  delete?: pulumi.Input<inputs.ExecCommandArgs>;
  deleteBeforeReplace?: pulumi.Input<boolean>;
  dir?: pulumi.Input<string>;
  environment?: pulumi.Input<{ [key: string]: pulumi.Input<string> }>;
  expandArgumentVars?: pulumi.Input<boolean>;
  logging?: pulumi.Input<string>;
  triggers?: pulumi.Input<inputs.TriggersInputArgs>;
  update?: pulumi.Input<inputs.ExecCommandArgs>;
}
