// Code generated by `python3 -m ansible.generate` DO NOT EDIT
package ansible

import (
	_ "embed"

	"github.com/sapslaj/mid/agent/rpc"
)

const CronName = "cron"

//go:embed cron.zip
var CronZipfile []byte

type CronParameters struct {
	Name         string  `json:"name"`
	User         *string `json:"user,omitempty"`
	Job          *string `json:"job,omitempty"`
	State        *string `json:"state,omitempty"`
	CronFile     *string `json:"cron_file,omitempty"`
	Backup       *bool   `json:"backup,omitempty"`
	Minute       *string `json:"minute,omitempty"`
	Hour         *string `json:"hour,omitempty"`
	Day          *string `json:"day,omitempty"`
	Month        *string `json:"month,omitempty"`
	Weekday      *string `json:"weekday,omitempty"`
	SpecialTime  *string `json:"special_time,omitempty"`
	Disabled     *bool   `json:"disabled,omitempty"`
	Env          *bool   `json:"env,omitempty"`
	Insertafter  *string `json:"insertafter,omitempty"`
	Insertbefore *string `json:"insertbefore,omitempty"`
}

func (p *CronParameters) ToRPCCall() (rpc.RPCCall[rpc.AnsiballZExecuteArgs], error) {
	args, err := rpc.AnyToJSONT[map[string]any](p)
	if err != nil {
		return rpc.RPCCall[rpc.AnsiballZExecuteArgs]{}, err
	}
	return rpc.RPCCall[rpc.AnsiballZExecuteArgs]{
		RPCFunction: rpc.RPCAnsiballZExecute,
		Args: rpc.AnsiballZExecuteArgs{
			Zip:  CronZipfile,
			Name: CronName,
			Args: args,
		},
	}, nil
}

type CronReturn struct {
	AnsibleCommonReturns
}

func CronReturnFromRPCResult(r rpc.RPCResult[rpc.AnsiballZExecuteResult]) (CronReturn, error) {
	return rpc.AnyToJSONT[CronReturn](r.Result.Result)
}
