// Code generated by `python3 -m ansible.generate` DO NOT EDIT
package ansible

import (
	_ "embed"
)

//go:embed deb822_repository.zip
var Deb822RepositoryZipfile []byte

type Deb822RepositoryParameters struct {
	AllowDowngradeToInsecure *bool     `json:"allow_downgrade_to_insecure,omitempty"`
	AllowInsecure            *bool     `json:"allow_insecure,omitempty"`
	AllowWeak                *bool     `json:"allow_weak,omitempty"`
	Architectures            *[]string `json:"architectures,omitempty"`
	ByHash                   *bool     `json:"by_hash,omitempty"`
	CheckDate                *bool     `json:"check_date,omitempty"`
	CheckValidUntil          *bool     `json:"check_valid_until,omitempty"`
	Components               *[]string `json:"components,omitempty"`
	DateMaxFuture            *int      `json:"date_max_future,omitempty"`
	Enabled                  *bool     `json:"enabled,omitempty"`
	InreleasePath            *string   `json:"inrelease_path,omitempty"`
	Languages                *[]string `json:"languages,omitempty"`
	Name                     string    `json:"name"`
	Pdiffs                   *bool     `json:"pdiffs,omitempty"`
	SignedBy                 *string   `json:"signed_by,omitempty"`
	Suites                   *[]string `json:"suites,omitempty"`
	Targets                  *[]string `json:"targets,omitempty"`
	Trusted                  *bool     `json:"trusted,omitempty"`
	Types                    *[]string `json:"types,omitempty"`
	Uris                     *[]string `json:"uris,omitempty"`
	Mode                     *any      `json:"mode,omitempty"`
	State                    *string   `json:"state,omitempty"`
}

type Deb822RepositoryReturn struct {
	AnsibleCommonReturns
	Repo        *string `json:"repo,omitempty"`
	Dest        *string `json:"dest,omitempty"`
	KeyFilename *string `json:"key_filename,omitempty"`
}
