// Code generated by ./hack/generate-ansible-types.py DO NOT EDIT
package ansible

import (
	"github.com/sapslaj/mid/agent/rpc"
	"github.com/sapslaj/mid/pkg/cast"
)

// Allows to run `docker container prune`, `docker image prune`, `docker network
// prune` and `docker volume prune` through the Docker API.
const DockerPruneName = "docker_prune"

// Parameters for the `docker_prune` Ansible module.
type DockerPruneParameters struct {
	// Whether to prune containers.
	// default: false
	Containers *bool `json:"containers,omitempty"`

	// A dictionary of filter values used for selecting containers to delete.
	// For example, `until: 24h`.
	// See `the docker documentation,https://docs.docker.com/engine/reference/comma
	// ndline/container_prune/#filtering` for more information on possible filters.
	ContainersFilters *map[string]any `json:"containers_filters,omitempty"`

	// Whether to prune images.
	// default: false
	Images *bool `json:"images,omitempty"`

	// A dictionary of filter values used for selecting images to delete.
	// For example, `dangling: true`.
	// See `the docker documentation,https://docs.docker.com/engine/reference/comma
	// ndline/image_prune/#filtering` for more information on possible filters.
	ImagesFilters *map[string]any `json:"images_filters,omitempty"`

	// Whether to prune networks.
	// default: false
	Networks *bool `json:"networks,omitempty"`

	// A dictionary of filter values used for selecting networks to delete.
	// See `the docker documentation,https://docs.docker.com/engine/reference/comma
	// ndline/network_prune/#filtering` for more information on possible filters.
	NetworksFilters *map[string]any `json:"networks_filters,omitempty"`

	// Whether to prune volumes.
	// default: false
	Volumes *bool `json:"volumes,omitempty"`

	// A dictionary of filter values used for selecting volumes to delete.
	// See `the docker documentation,https://docs.docker.com/engine/reference/comma
	// ndline/volume_prune/#filtering` for more information on possible filters.
	VolumesFilters *map[string]any `json:"volumes_filters,omitempty"`

	// Whether to prune the builder cache.
	// default: false
	BuilderCache *bool `json:"builder_cache,omitempty"`

	// Whether to remove all types of build cache.
	// default: false
	BuilderCacheAll *bool `json:"builder_cache_all,omitempty"`

	// A dictionary of filter values used for selecting images to delete.
	// For example, `until: 10m`.
	// See `the API documentation,https://docs.docker.com/engine/api/v1.44/#tag/Ima
	// ge/operation/BuildPrune` for more information on possible filters.
	BuilderCacheFilters *map[string]any `json:"builder_cache_filters,omitempty"`

	// Amount of disk space to keep for cache in format `<number>[<unit>]`.".
	// Number is a positive integer. Unit can be one of `B` (byte), `K` (kibibyte,
	// 1024B), `M` (mebibyte), `G` (gibibyte), `T` (tebibyte), or `P` (pebibyte).
	// Omitting the unit defaults to bytes.
	BuilderCacheKeepStorage *string `json:"builder_cache_keep_storage,omitempty"`

	// The URL or Unix socket path used to connect to the Docker API. To connect to
	// a remote host, provide the TCP connection string. For example,
	// `tcp://192.0.2.23:2376`. If TLS is used to encrypt the connection, the
	// module will automatically replace `tcp` in the connection URL with `https`.
	// If the value is not specified in the task, the value of environment variable
	// `DOCKER_HOST` will be used instead. If the environment variable is not set,
	// the default value will be used.
	// default: "unix:///var/run/docker.sock"
	DockerHost *string `json:"docker_host,omitempty"`

	// When verifying the authenticity of the Docker Host server, provide the
	// expected name of the server.
	// If the value is not specified in the task, the value of environment variable
	// `DOCKER_TLS_HOSTNAME` will be used instead. If the environment variable is
	// not set, the default value will be used.
	// Note that this option had a default value `localhost` in older versions. It
	// was removed in community.docker 3.0.0.
	TlsHostname *string `json:"tls_hostname,omitempty"`

	// The version of the Docker API running on the Docker Host.
	// Defaults to the latest version of the API supported by this collection and
	// the docker daemon.
	// If the value is not specified in the task, the value of environment variable
	// `DOCKER_API_VERSION` will be used instead. If the environment variable is
	// not set, the default value will be used.
	// default: "auto"
	ApiVersion *string `json:"api_version,omitempty"`

	// The maximum amount of time in seconds to wait on a response from the API.
	// If the value is not specified in the task, the value of environment variable
	// `DOCKER_TIMEOUT` will be used instead. If the environment variable is not
	// set, the default value will be used.
	// default: 60
	Timeout *int `json:"timeout,omitempty"`

	// Use a CA certificate when performing server verification by providing the
	// path to a CA certificate file.
	// If the value is not specified in the task and the environment variable
	// `DOCKER_CERT_PATH` is set, the file `ca.pem` from the directory specified in
	// the environment variable `DOCKER_CERT_PATH` will be used.
	// This option was called `ca_cert` and got renamed to `ca_path` in
	// community.docker 3.6.0. The old name has been added as an alias and can
	// still be used.
	CaPath *string `json:"ca_path,omitempty"`

	// Path to the client's TLS certificate file.
	// If the value is not specified in the task and the environment variable
	// `DOCKER_CERT_PATH` is set, the file `cert.pem` from the directory specified
	// in the environment variable `DOCKER_CERT_PATH` will be used.
	ClientCert *string `json:"client_cert,omitempty"`

	// Path to the client's TLS key file.
	// If the value is not specified in the task and the environment variable
	// `DOCKER_CERT_PATH` is set, the file `key.pem` from the directory specified
	// in the environment variable `DOCKER_CERT_PATH` will be used.
	ClientKey *string `json:"client_key,omitempty"`

	// Secure the connection to the API by using TLS without verifying the
	// authenticity of the Docker host server. Note that if `validate_certs` is set
	// to `true` as well, it will take precedence.
	// If the value is not specified in the task, the value of environment variable
	// `DOCKER_TLS` will be used instead. If the environment variable is not set,
	// the default value will be used.
	// default: false
	Tls *bool `json:"tls,omitempty"`

	// For SSH transports, use the `ssh` CLI tool instead of paramiko.
	// default: false
	UseSshClient *bool `json:"use_ssh_client,omitempty"`

	// Secure the connection to the API by using TLS and verifying the authenticity
	// of the Docker host server.
	// If the value is not specified in the task, the value of environment variable
	// `DOCKER_TLS_VERIFY` will be used instead. If the environment variable is not
	// set, the default value will be used.
	// default: false
	ValidateCerts *bool `json:"validate_certs,omitempty"`

	// Debug mode
	// default: false
	Debug *bool `json:"debug,omitempty"`
}

// Wrap the `DockerPruneParameters into an `rpc.RPCCall`.
func (p DockerPruneParameters) ToRPCCall() (rpc.RPCCall[rpc.AnsibleExecuteArgs], error) {
	args, err := cast.AnyToJSONT[map[string]any](p)
	if err != nil {
		return rpc.RPCCall[rpc.AnsibleExecuteArgs]{}, err
	}
	return rpc.RPCCall[rpc.AnsibleExecuteArgs]{
		RPCFunction: rpc.RPCAnsibleExecute,
		Args: rpc.AnsibleExecuteArgs{
			Name: DockerPruneName,
			Args: args,
		},
	}, nil
}

// Return values for the `docker_prune` Ansible module.
type DockerPruneReturn struct {
	AnsibleCommonReturns

	// List of IDs of deleted containers.
	Containers *[]string `json:"containers,omitempty"`

	// Amount of reclaimed disk space from container pruning in bytes.
	ContainersSpaceReclaimed *int `json:"containers_space_reclaimed,omitempty"`

	// List of IDs of deleted images.
	Images *[]string `json:"images,omitempty"`

	// Amount of reclaimed disk space from image pruning in bytes.
	ImagesSpaceReclaimed *int `json:"images_space_reclaimed,omitempty"`

	// List of IDs of deleted networks.
	Networks *[]string `json:"networks,omitempty"`

	// List of IDs of deleted volumes.
	Volumes *[]string `json:"volumes,omitempty"`

	// Amount of reclaimed disk space from volumes pruning in bytes.
	VolumesSpaceReclaimed *int `json:"volumes_space_reclaimed,omitempty"`

	// Amount of reclaimed disk space from builder cache pruning in bytes.
	BuilderCacheSpaceReclaimed *int `json:"builder_cache_space_reclaimed,omitempty"`

	// The build caches that were deleted.
	BuilderCacheCachesDeleted *[]string `json:"builder_cache_caches_deleted,omitempty"`
}

// Unwrap the `rpc.RPCResult` into an `DockerPruneReturn`
func DockerPruneReturnFromRPCResult(r rpc.RPCResult[rpc.AnsibleExecuteResult]) (DockerPruneReturn, error) {
	return cast.AnyToJSONT[DockerPruneReturn](r.Result.Result)
}
