// Code generated by `python3 -m ansible.generate` DO NOT EDIT
package ansible

import (
	_ "embed"
)

//go:embed expect.zip
var ExpectZipfile []byte

type ExpectParameters struct {
	Command   string         `json:"command"`
	Creates   *string        `json:"creates,omitempty"`
	Removes   *string        `json:"removes,omitempty"`
	Chdir     *string        `json:"chdir,omitempty"`
	Responses map[string]any `json:"responses"`
	Timeout   *any           `json:"timeout,omitempty"`
	Echo      *bool          `json:"echo,omitempty"`
}

type ExpectReturn struct {
	AnsibleCommonReturns
}
