// Code generated by `python3 -m ansible.generate` DO NOT EDIT
package ansible

import (
	_ "embed"
)

//go:embed file.zip
var FileZipfile []byte

type FileParameters struct {
	Path                   string  `json:"path"`
	State                  *string `json:"state,omitempty"`
	Src                    *string `json:"src,omitempty"`
	Recurse                *bool   `json:"recurse,omitempty"`
	Force                  *bool   `json:"force,omitempty"`
	Follow                 *bool   `json:"follow,omitempty"`
	ModificationTime       *string `json:"modification_time,omitempty"`
	ModificationTimeFormat *string `json:"modification_time_format,omitempty"`
	AccessTime             *string `json:"access_time,omitempty"`
	AccessTimeFormat       *string `json:"access_time_format,omitempty"`
}

type FileReturn struct {
	AnsibleCommonReturns
	Dest *string `json:"dest,omitempty"`
	Path *string `json:"path,omitempty"`
}
