// Code generated by `python3 -m ansible.generate` DO NOT EDIT
package ansible

import (
	_ "embed"
)

//go:embed get_url.zip
var GetUrlZipfile []byte

type GetUrlParameters struct {
	Ciphers             *[]string       `json:"ciphers,omitempty"`
	Decompress          *bool           `json:"decompress,omitempty"`
	Url                 string          `json:"url"`
	Dest                string          `json:"dest"`
	TmpDest             *string         `json:"tmp_dest,omitempty"`
	Force               *bool           `json:"force,omitempty"`
	Backup              *bool           `json:"backup,omitempty"`
	Checksum            *string         `json:"checksum,omitempty"`
	UseProxy            *bool           `json:"use_proxy,omitempty"`
	ValidateCerts       *bool           `json:"validate_certs,omitempty"`
	Timeout             *int            `json:"timeout,omitempty"`
	Headers             *map[string]any `json:"headers,omitempty"`
	UrlUsername         *string         `json:"url_username,omitempty"`
	UrlPassword         *string         `json:"url_password,omitempty"`
	ForceBasicAuth      *bool           `json:"force_basic_auth,omitempty"`
	ClientCert          *string         `json:"client_cert,omitempty"`
	ClientKey           *string         `json:"client_key,omitempty"`
	HttpAgent           *string         `json:"http_agent,omitempty"`
	UnredirectedHeaders *[]string       `json:"unredirected_headers,omitempty"`
	UseGssapi           *bool           `json:"use_gssapi,omitempty"`
	UseNetrc            *bool           `json:"use_netrc,omitempty"`
}

type GetUrlReturn struct {
	AnsibleCommonReturns
	BackupFile   *string `json:"backup_file,omitempty"`
	ChecksumDest *string `json:"checksum_dest,omitempty"`
	ChecksumSrc  *string `json:"checksum_src,omitempty"`
	Dest         *string `json:"dest,omitempty"`
	Elapsed      *int    `json:"elapsed,omitempty"`
	Gid          *int    `json:"gid,omitempty"`
	Group        *string `json:"group,omitempty"`
	Md5sum       *string `json:"md5sum,omitempty"`
	Mode         *string `json:"mode,omitempty"`
	Msg          *string `json:"msg,omitempty"`
	Owner        *string `json:"owner,omitempty"`
	Secontext    *string `json:"secontext,omitempty"`
	Size         *int    `json:"size,omitempty"`
	Src          *string `json:"src,omitempty"`
	State        *string `json:"state,omitempty"`
	StatusCode   *int    `json:"status_code,omitempty"`
	Uid          *int    `json:"uid,omitempty"`
	Url          *string `json:"url,omitempty"`
}
