// Code generated by `python3 -m ansible.generate` DO NOT EDIT
package ansible

import (
	_ "embed"
)

//go:embed lineinfile.zip
var LineinfileZipfile []byte

type LineinfileParameters struct {
	Path         string  `json:"path"`
	Regexp       *string `json:"regexp,omitempty"`
	SearchString *string `json:"search_string,omitempty"`
	State        *string `json:"state,omitempty"`
	Line         *string `json:"line,omitempty"`
	Backrefs     *bool   `json:"backrefs,omitempty"`
	Insertafter  *string `json:"insertafter,omitempty"`
	Insertbefore *string `json:"insertbefore,omitempty"`
	Create       *bool   `json:"create,omitempty"`
	Backup       *bool   `json:"backup,omitempty"`
	Firstmatch   *bool   `json:"firstmatch,omitempty"`
}

type LineinfileReturn struct {
	AnsibleCommonReturns
}
