// Code generated by ./hack/generate-ansible-types.py DO NOT EDIT
package ansible

import (
	"github.com/sapslaj/mid/agent/rpc"
)

// This module renames volume groups using the `vgchange` command.
const LvgRenameName = "lvg_rename"

// Parameters for the `lvg_rename` Ansible module.
type LvgRenameParameters struct {
	// The name or UUID of the source VG.
	// See `vgrename(8\`) for valid values.
	Vg string `json:"vg"`

	// The new name of the VG.
	// See `lvm(8\`) for valid names.
	VgNew string `json:"vg_new"`
}

// Wrap the `LvgRenameParameters into an `rpc.RPCCall`.
func (p LvgRenameParameters) ToRPCCall() (rpc.RPCCall[rpc.AnsibleExecuteArgs], error) {
	args, err := rpc.AnyToJSONT[map[string]any](p)
	if err != nil {
		return rpc.RPCCall[rpc.AnsibleExecuteArgs]{}, err
	}
	return rpc.RPCCall[rpc.AnsibleExecuteArgs]{
		RPCFunction: rpc.RPCAnsibleExecute,
		Args: rpc.AnsibleExecuteArgs{
			Name: LvgRenameName,
			Args: args,
		},
	}, nil
}

// Return values for the `lvg_rename` Ansible module.
type LvgRenameReturn struct {
	AnsibleCommonReturns
}

// Unwrap the `rpc.RPCResult` into an `LvgRenameReturn`
func LvgRenameReturnFromRPCResult(r rpc.RPCResult[rpc.AnsibleExecuteResult]) (LvgRenameReturn, error) {
	return rpc.AnyToJSONT[LvgRenameReturn](r.Result.Result)
}
