// Code generated by `python3 -m ansible.generate` DO NOT EDIT
package ansible

import (
	_ "embed"
)

//go:embed mount_facts.zip
var MountFactsZipfile []byte

type MountFactsParameters struct {
	Devices                *[]string `json:"devices,omitempty"`
	Fstypes                *[]string `json:"fstypes,omitempty"`
	Sources                *[]string `json:"sources,omitempty"`
	MountBinary            *any      `json:"mount_binary,omitempty"`
	Timeout                *float64  `json:"timeout,omitempty"`
	OnTimeout              *string   `json:"on_timeout,omitempty"`
	IncludeAggregateMounts *bool     `json:"include_aggregate_mounts,omitempty"`
}

type MountFactsReturn struct {
	AnsibleCommonReturns
	AnsibleFacts *map[string]any `json:"ansible_facts,omitempty"`
}
