// Code generated by `python3 -m ansible.generate` DO NOT EDIT
package ansible

import (
	_ "embed"
)

//go:embed package_facts.zip
var PackageFactsZipfile []byte

type PackageFactsParameters struct {
	Manager  *[]string `json:"manager,omitempty"`
	Strategy *string   `json:"strategy,omitempty"`
}

type PackageFactsReturn struct {
	AnsibleCommonReturns
	AnsibleFacts *any `json:"ansible_facts,omitempty"`
}
