// Code generated by ./hack/generate-ansible-types.py DO NOT EDIT
package ansible

import (
	"github.com/sapslaj/mid/agent/rpc"
)

const PingName = "ping"

type PingParameters struct {
	Data *string `json:"data,omitempty"`
}

func (p *PingParameters) ToRPCCall() (rpc.RPCCall[rpc.AnsibleExecuteArgs], error) {
	args, err := rpc.AnyToJSONT[map[string]any](p)
	if err != nil {
		return rpc.RPCCall[rpc.AnsibleExecuteArgs]{}, err
	}
	return rpc.RPCCall[rpc.AnsibleExecuteArgs]{
		RPCFunction: rpc.RPCAnsibleExecute,
		Args: rpc.AnsibleExecuteArgs{
			Name: PingName,
			Args: args,
		},
	}, nil
}

type PingReturn struct {
	AnsibleCommonReturns
	Ping *string `json:"ping,omitempty"`
}

func PingReturnFromRPCResult(r rpc.RPCResult[rpc.AnsibleExecuteResult]) (PingReturn, error) {
	return rpc.AnyToJSONT[PingReturn](r.Result.Result)
}
