// Code generated by `python3 -m ansible.generate` DO NOT EDIT
package ansible

import (
	_ "embed"
)

//go:embed pip.zip
var PipZipfile []byte

type PipParameters struct {
	Name                   *[]string `json:"name,omitempty"`
	Version                *string   `json:"version,omitempty"`
	Requirements           *string   `json:"requirements,omitempty"`
	Virtualenv             *string   `json:"virtualenv,omitempty"`
	VirtualenvSitePackages *bool     `json:"virtualenv_site_packages,omitempty"`
	VirtualenvCommand      *string   `json:"virtualenv_command,omitempty"`
	VirtualenvPython       *string   `json:"virtualenv_python,omitempty"`
	State                  *string   `json:"state,omitempty"`
	ExtraArgs              *string   `json:"extra_args,omitempty"`
	Editable               *bool     `json:"editable,omitempty"`
	Chdir                  *string   `json:"chdir,omitempty"`
	Executable             *string   `json:"executable,omitempty"`
	Umask                  *string   `json:"umask,omitempty"`
	BreakSystemPackages    *bool     `json:"break_system_packages,omitempty"`
}

type PipReturn struct {
	AnsibleCommonReturns
	Cmd          *string `json:"cmd,omitempty"`
	Name         *[]any  `json:"name,omitempty"`
	Requirements *string `json:"requirements,omitempty"`
	Version      *string `json:"version,omitempty"`
	Virtualenv   *string `json:"virtualenv,omitempty"`
}
