// Code generated by `python3 -m ansible.generate` DO NOT EDIT
package ansible

import (
	_ "embed"
)

//go:embed replace.zip
var ReplaceZipfile []byte

type ReplaceParameters struct {
	Path     string  `json:"path"`
	Regexp   string  `json:"regexp"`
	Replace  *string `json:"replace,omitempty"`
	After    *string `json:"after,omitempty"`
	Before   *string `json:"before,omitempty"`
	Backup   *bool   `json:"backup,omitempty"`
	Encoding *string `json:"encoding,omitempty"`
}

type ReplaceReturn struct {
	AnsibleCommonReturns
}
