// Code generated by `python3 -m ansible.generate` DO NOT EDIT
package ansible

import (
	_ "embed"
)

//go:embed rpm_key.zip
var RpmKeyZipfile []byte

type RpmKeyParameters struct {
	Key           string    `json:"key"`
	State         *string   `json:"state,omitempty"`
	ValidateCerts *bool     `json:"validate_certs,omitempty"`
	Fingerprint   *[]string `json:"fingerprint,omitempty"`
}

type RpmKeyReturn struct {
	AnsibleCommonReturns
}
