// Code generated by ./hack/generate-ansible-types.py DO NOT EDIT
package ansible

import (
	"github.com/sapslaj/mid/agent/rpc"
)

const StatName = "stat"

type StatParameters struct {
	Path              string  `json:"path"`
	Follow            *bool   `json:"follow,omitempty"`
	GetChecksum       *bool   `json:"get_checksum,omitempty"`
	ChecksumAlgorithm *string `json:"checksum_algorithm,omitempty"`
	GetMime           *bool   `json:"get_mime,omitempty"`
	GetAttributes     *bool   `json:"get_attributes,omitempty"`
}

func (p *StatParameters) ToRPCCall() (rpc.RPCCall[rpc.AnsibleExecuteArgs], error) {
	args, err := rpc.AnyToJSONT[map[string]any](p)
	if err != nil {
		return rpc.RPCCall[rpc.AnsibleExecuteArgs]{}, err
	}
	return rpc.RPCCall[rpc.AnsibleExecuteArgs]{
		RPCFunction: rpc.RPCAnsibleExecute,
		Args: rpc.AnsibleExecuteArgs{
			Name: StatName,
			Args: args,
		},
	}, nil
}

type StatReturn struct {
	AnsibleCommonReturns
	Stat *map[string]any `json:"stat,omitempty"`
}

func StatReturnFromRPCResult(r rpc.RPCResult[rpc.AnsibleExecuteResult]) (StatReturn, error) {
	return rpc.AnyToJSONT[StatReturn](r.Result.Result)
}
