// Code generated by `python3 -m ansible.generate` DO NOT EDIT
package ansible

import (
	_ "embed"
)

//go:embed stat.zip
var StatZipfile []byte

type StatParameters struct {
	Path              string  `json:"path"`
	Follow            *bool   `json:"follow,omitempty"`
	GetChecksum       *bool   `json:"get_checksum,omitempty"`
	ChecksumAlgorithm *string `json:"checksum_algorithm,omitempty"`
	GetMime           *bool   `json:"get_mime,omitempty"`
	GetAttributes     *bool   `json:"get_attributes,omitempty"`
}

type StatReturn struct {
	AnsibleCommonReturns
	Stat *map[string]any `json:"stat,omitempty"`
}
