// Code generated by `python3 -m ansible.generate` DO NOT EDIT
package ansible

import (
	_ "embed"
)

//go:embed subversion.zip
var SubversionZipfile []byte

type SubversionParameters struct {
	Repo          string  `json:"repo"`
	Dest          *string `json:"dest,omitempty"`
	Revision      *string `json:"revision,omitempty"`
	Force         *bool   `json:"force,omitempty"`
	InPlace       *bool   `json:"in_place,omitempty"`
	Username      *string `json:"username,omitempty"`
	Password      *string `json:"password,omitempty"`
	Executable    *string `json:"executable,omitempty"`
	Checkout      *bool   `json:"checkout,omitempty"`
	Update        *bool   `json:"update,omitempty"`
	Export        *bool   `json:"export,omitempty"`
	Switch        *bool   `json:"switch,omitempty"`
	ValidateCerts *bool   `json:"validate_certs,omitempty"`
}

type SubversionReturn struct {
	AnsibleCommonReturns
}
