// Code generated by `python3 -m ansible.generate` DO NOT EDIT
package ansible

import (
	_ "embed"

	"github.com/sapslaj/mid/agent/rpc"
)

const TempfileName = "tempfile"

//go:embed tempfile.zip
var TempfileZipfile []byte

type TempfileParameters struct {
	State  *string `json:"state,omitempty"`
	Path   *string `json:"path,omitempty"`
	Prefix *string `json:"prefix,omitempty"`
	Suffix *string `json:"suffix,omitempty"`
}

func (p *TempfileParameters) ToRPCCall() (rpc.RPCCall[rpc.AnsiballZExecuteArgs], error) {
	args, err := rpc.AnyToJSONT[map[string]any](p)
	if err != nil {
		return rpc.RPCCall[rpc.AnsiballZExecuteArgs]{}, err
	}
	return rpc.RPCCall[rpc.AnsiballZExecuteArgs]{
		RPCFunction: rpc.RPCAnsiballZExecute,
		Args: rpc.AnsiballZExecuteArgs{
			Zip:  TempfileZipfile,
			Name: TempfileName,
			Args: args,
		},
	}, nil
}

type TempfileReturn struct {
	AnsibleCommonReturns
	Path *string `json:"path,omitempty"`
}

func TempfileReturnFromRPCResult(r rpc.RPCResult[rpc.AnsiballZExecuteResult]) (TempfileReturn, error) {
	return rpc.AnyToJSONT[TempfileReturn](r.Result.Result)
}
