// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Mid.Types.Outputs
{

    [OutputType]
    public sealed class TriggersOutput
    {
        public readonly string LastChanged;
        public readonly ImmutableArray<object> Refresh;
        public readonly ImmutableArray<object> Replace;

        [OutputConstructor]
        private TriggersOutput(
            string lastChanged,

            ImmutableArray<object> refresh,

            ImmutableArray<object> replace)
        {
            LastChanged = lastChanged;
            Refresh = refresh;
            Replace = replace;
        }
    }
}
