// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
	"github.com/sapslaj/mid/sdk/go/mid/internal"
)

var _ = internal.GetEnvOrDefault

// remote endpoint connection configuration
func GetConnection(ctx *pulumi.Context) string {
	return config.Get(ctx, "mid:connection")
}

// If present and set to true, the provider will delete resources associated
// with an unreachable remote endpoint from Pulumi state. It can also be
// sourced from the following environment variable:`PULUMI_MID_DELETE_UNREACHABLE`
func GetDeleteUnreachable(ctx *pulumi.Context) bool {
	return config.GetBool(ctx, "mid:deleteUnreachable")
}
func GetParallel(ctx *pulumi.Context) int {
	return config.GetInt(ctx, "mid:parallel")
}
