name: Setup tools
description: Installs Go, Pulumi, pulumictl, schema-tools, Node.JS, Python, dotnet and Java.

inputs:
  tools:
    description: |
      Comma separated list of tools to install. The default of "all" installs all tools. Available tools are:
        go
        just
        nodejs
        pulumicli
        pulumictl
        schema-tools
    default: all

runs:
  using: "composite"
  steps:
    - name: Install Go
      if: inputs.tools == 'all' || contains(inputs.tools, 'go')
      uses: actions/setup-go@v5
      with:
        go-version: "1.24.x"
        cache-dependency-path: |
          provider/*.sum
          upstream/*.sum
          sdk/*.sum

    - name: Install Just
      if: inputs.tools == 'all' || contains(inputs.tools, 'just')
      uses: extractions/setup-just@v3

    - name: Setup Node
      if: inputs.tools == 'all' || contains(inputs.tools, 'nodejs')
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        registry-url: https://registry.npmjs.org

    - name: Install pulumictl
      if: inputs.tools == 'all' || contains(inputs.tools, 'pulumictl')
      uses: jaxxstorm/action-install-gh-release@v1.11.0
      with:
        tag: v0.0.46
        repo: pulumi/pulumictl

    - name: Install Pulumi CLI
      if: inputs.tools == 'all' || contains(inputs.tools, 'pulumicli')
      uses: pulumi/actions@9519177da243fd32cab35cdbf19cce1ab7472fcc # v6
      with:
        pulumi-version: "dev"

    - name: Install Schema Tools
      if: inputs.tools == 'all' || contains(inputs.tools, 'schema-tools')
      uses: jaxxstorm/action-install-gh-release@v1.11.0
      with:
        repo: pulumi/schema-tools
