from io import StringIO
import multiprocessing
import os
import time
from typing import Any
import zipfile
from importlib import import_module

import yaml
from ansible.executor.module_common import recursive_finder, _make_zinfo


def pascalcased(s: str) -> str:
    return "".join([word.capitalize() for word in s.split("_")])


def yaml_loads(data: Any) -> Any:
    yaml.safe_load(StringIO(data))
    return


def scalar_type_ansible_to_go(t: str) -> str:
    match t:
        case "str":
            return "string"
        case "path":
            return "string"
        case "bool":
            return "bool"
        case "int":
            return "int"
        case "raw":
            # TODO: should this be a string instead or something?
            return "any"
        case "float":
            return "float64"
        case _:
            raise Exception(f"unknown type '{t}'")


def composite_type_ansible_to_go(obj: Any) -> str:
    typ = obj.get("type", "str")
    match typ:
        case "complex":
            # TODO: handle this better
            return "any"
        case "list":
            elements = obj.get("elements", None)
            if not elements:
                return "[]any"
            return "[]" + scalar_type_ansible_to_go(elements)
        case "dict":
            if obj.get("elements", None) is not None:
                raise Exception("dict has subelements???")
            suboptions = obj.get("suboptions", None)
            if not suboptions:
                return "map[string]any"
            result = "struct {"
            for key, value in suboptions.items():
                required = value.get("required", False)
                result += "\t\t"
                result += pascalcased(key)
                result += " "
                if not required:
                    result += "*"
                result += composite_type_ansible_to_go(value)
                result += ' `json:"'
                result += key
                if not required:
                    result += ",omitempty"
                result += '"`\n'

            result += "\t}"
            return result
        case _:
            return scalar_type_ansible_to_go(typ)


def process_module_file(module_file: str):
    date_time = time.gmtime()[:6]
    if module_file.startswith("_"):
        return
    name = os.path.splitext(module_file)[0]
    module_fqn = f"ansible.modules.{name}"
    with open(
        os.path.join(os.path.dirname(__file__), "modules", module_file), "rb"
    ) as f:
        module_data = f.read()

    # TODO: tunable compression
    zf = zipfile.ZipFile(
        file=os.path.join(
            os.path.dirname(__file__), "..", "agent", "ansible", f"{name}.zip"
        ),
        mode="w",
    )

    zf.writestr(
        _make_zinfo(
            filename=f"ansible/modules/{module_file}", date_time=date_time, zf=zf
        ),
        module_data,
    )
    recursive_finder(
        name=name,
        module_fqn=module_fqn,
        module_data=module_data,
        zf=zf,
        date_time=date_time,
    )
    zf.close()

    module = import_module(module_fqn)
    documentation = yaml.safe_load(StringIO(getattr(module, "DOCUMENTATION")))
    returns = yaml.safe_load(StringIO(getattr(module, "RETURN", "{}")))
    if returns is None:
        returns = dict()

    pascalcase_name = pascalcased(name)

    print(name)

    with open(
        os.path.join(os.path.dirname(__file__), "..", "agent", "ansible", f"{name}.go"),
        "w",
    ) as f:
        f.write("// Code generated by `python3 -m ansible.generate` DO NOT EDIT\n")
        f.write("package ansible\n\n")
        f.write("import (\n")
        f.write('\t_ "embed"\n')
        f.write(")\n\n")
        f.write(f"//go:embed {name}.zip\n")
        f.write(f"var {pascalcase_name}Zipfile []byte\n\n")
        f.write(f"type {pascalcase_name}Parameters struct {'{'}\n")
        for key, value in documentation["options"].items():
            required = value.get("required", False)
            f.write("\t")
            f.write(pascalcased(key))
            f.write(" ")
            if not required:
                f.write("*")
            f.write(composite_type_ansible_to_go(value))
            f.write(' `json:"')
            f.write(key)
            if not required:
                f.write(",omitempty")
            f.write('"`\n')
        f.write("}\n\n")
        f.write(f"type {pascalcase_name}Return struct {'{'}\n")
        f.write("\tAnsibleCommonReturns\n")
        for key, value in returns.items():
            f.write("\t")
            f.write(pascalcased(key))
            f.write(" *")
            f.write(composite_type_ansible_to_go(value))
            f.write(' `json:"')
            f.write(key)
            f.write(",omitempty")
            f.write('"`\n')
        f.write("}\n")


def main():
    with multiprocessing.Pool(os.process_cpu_count()) as p:
        p.map(
            process_module_file,
            os.listdir(os.path.join(os.path.dirname(__file__), "modules")),
        )


if __name__ == "__main__":
    main()
