// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

import * as utilities from "../utilities";

/**
 * Instructions for how to connect to a remote endpoint.
 */
export interface Connection {
  /**
   * The address of the resource to connect to.
   */
  host?: string;
  hostKey?: string;
  /**
   * The password we should use for the connection.
   */
  password?: string;
  perDialTimeout?: number;
  /**
   * The port to connect to. Defaults to 22.
   */
  port?: number;
  /**
   * The contents of an SSH key to use for the
   * connection. This takes preference over the password if provided.
   */
  privateKey?: string;
  privateKeyPassword?: string;
  sshAgent?: boolean;
  sshAgentSocketPath?: string;
  /**
   * The user that we should use for the connection.
   */
  user?: string;
}
/**
 * connectionProvideDefaults sets the appropriate defaults for Connection
 */
export function connectionProvideDefaults(val: Connection): Connection {
  return {
    ...val,
    port: (val.port) ?? 22,
    user: (val.user) ?? "root",
  };
}

/**
 * Instructions for how to connect to a remote endpoint.
 */
export interface ConnectionArgs {
  /**
   * The address of the resource to connect to.
   */
  host?: pulumi.Input<string | undefined>;
  hostKey?: pulumi.Input<string | undefined>;
  /**
   * The password we should use for the connection.
   */
  password?: pulumi.Input<string | undefined>;
  perDialTimeout?: pulumi.Input<number | undefined>;
  /**
   * The port to connect to. Defaults to 22.
   */
  port?: pulumi.Input<number | undefined>;
  /**
   * The contents of an SSH key to use for the
   * connection. This takes preference over the password if provided.
   */
  privateKey?: pulumi.Input<string | undefined>;
  privateKeyPassword?: pulumi.Input<string | undefined>;
  sshAgent?: pulumi.Input<boolean | undefined>;
  sshAgentSocketPath?: pulumi.Input<string | undefined>;
  /**
   * The user that we should use for the connection.
   */
  user?: pulumi.Input<string | undefined>;
}
/**
 * connectionArgsProvideDefaults sets the appropriate defaults for ConnectionArgs
 */
export function connectionArgsProvideDefaults(val: ConnectionArgs): ConnectionArgs {
  return {
    ...val,
    port: (val.port) ?? 22,
    user: (val.user) ?? "root",
  };
}

export interface ExecCommandArgs {
  /**
   * List of arguments to execute. Under the hood, these are passed to `execve`, bypassing any shell
   */
  command: pulumi.Input<pulumi.Input<string>[]>;
  /**
   * Directory path to chdir to before executing the command. Defaults to the
   * default working directory for the SSH user and session, usually the user's
   * home.
   */
  dir?: pulumi.Input<string | undefined>;
  /**
   * Key-value pairs of environment variables to pass to the process. These are
   * merged with any system-wide environment variables.
   */
  environment?: pulumi.Input<{ [key: string]: pulumi.Input<string> } | undefined>;
  /**
   * Pass a string to the command's process as standard in.
   */
  stdin?: pulumi.Input<string | undefined>;
}

export interface ResourceConfig {
  check?: boolean;
  deleteUnreachable?: boolean;
  parallel?: number;
}

export interface ResourceConfigArgs {
  check?: pulumi.Input<boolean | undefined>;
  deleteUnreachable?: pulumi.Input<boolean | undefined>;
  parallel?: pulumi.Input<number | undefined>;
}

export interface TriggersInputArgs {
  /**
   * Run any "refresh" operations (e.g. service restarts, change diffs, etc) if
   * any value in this list changes.
   */
  refresh?: pulumi.Input<any[] | undefined>;
  /**
   * Completely delete and replace the resource if any value in this list
   * changes.
   */
  replace?: pulumi.Input<any[] | undefined>;
}

export namespace resource {
  export interface AnsibleTaskListArgsTaskArgs {
    args: pulumi.Input<{ [key: string]: any }>;
    check?: pulumi.Input<boolean | undefined>;
    environment?: pulumi.Input<{ [key: string]: pulumi.Input<string> } | undefined>;
    ignoreErrors?: pulumi.Input<boolean | undefined>;
    module: pulumi.Input<string>;
  }

  export interface AnsibleTaskListArgsTasksArgs {
    create: pulumi.Input<pulumi.Input<inputs.resource.AnsibleTaskListArgsTaskArgs>[]>;
    delete?: pulumi.Input<pulumi.Input<inputs.resource.AnsibleTaskListArgsTaskArgs>[] | undefined>;
    update?: pulumi.Input<pulumi.Input<inputs.resource.AnsibleTaskListArgsTaskArgs>[] | undefined>;
  }
}
