# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins
import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload

if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities
from .. import types as _types

connection: Optional[str]
"""
remote endpoint connection configuration
"""

deleteUnreachable: Optional[bool]
"""
If present and set to true, the provider will delete resources associated
with an unreachable remote endpoint from Pulumi state. It can also be
sourced from the following environment variable:`PULUMI_MID_DELETE_UNREACHABLE`
"""

parallel: Optional[int]
