# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload

if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities
from .. import outputs as _root_outputs

import types

__config__ = pulumi.Config("mid")


class _ExportableConfig(types.ModuleType):
    @_builtins.property
    def connection(self) -> Optional[str]:
        return __config__.get("connection")

    @_builtins.property
    def delete_unreachable(self) -> Optional[bool]:
        return __config__.get_bool("deleteUnreachable")

    @_builtins.property
    def parallel(self) -> Optional[int]:
        return __config__.get_int("parallel")
