name: Build/Test

on:
  workflow_dispatch:
  push:

env:
  GOPRIVATE: github.com/sapslaj

jobs:
  build-provider:
    name: build-provider
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goarch:
          - amd64
          - arm64
        goos:
          - linux
          - windows
          - darwin
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        id: git
        with:
          submodules: "recursive"
          fetch-depth: 0
          fetch-tags: true
      - name: Setup tools
        uses: ./.github/actions/setup-tools
        with:
          tools: just, go
      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: "0"
        run: |
          set -eux
          just provider
          file ./bin/pulumi-resource-mid

  smoketest:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      actions: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        id: git
        with:
          submodules: "recursive"
          fetch-depth: 0
          fetch-tags: true
      - name: Setup tools
        uses: ./.github/actions/setup-tools
        with:
          tools: all
      - name: Run smoketest container
        run: |
          docker build -t mid-smoketest docker/smoketest/
          docker run -p 2222:22 --name mid-smoketest -d mid-smoketest
      - name: Build
        id: build
        run: just build
      - name: Install
        id: install
        run: just install
      - name: PulumiUp
        id: up
        run: just test-example-up
      - name: PulumiDown
        id: down
        run: just test-example-down

  test-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup tools
        uses: ./.github/actions/setup-tools
        with:
          tools: just, go, python
      - run: just provider_version=v0.0.0-ci agent-gogenerate
      - run: go test -timeout=1h -v -race ./provider/...

  test-integration:
    runs-on: ubuntu-latest
    services:
      dind:
        image: docker:23.0-rc-dind-rootless
        ports:
          - 2375:2375
    steps:
      - uses: actions/checkout@v4
      - name: Setup tools
        uses: ./.github/actions/setup-tools
        with:
          tools: just, go, python
      - run: just provider_version=v0.0.0-ci agent-gogenerate
      - run: go test -timeout=1h -v -race ./tests/...
