name: Build/Test

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      actions: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        id: git
        with:
          submodules: "recursive"
          fetch-depth: 0
          fetch-tags: true
      - name: Setup tools
        uses: ./.github/actions/setup-tools
        with:
          tools: just, go, pulumicli, pulumictl, nodejs, python, dotnet
      - name: Run smoketest container
        run: |
          docker build -t mid-smoketest docker/smoketest/
          docker run -p 2222:22 --name mid-smoketest -d mid-smoketest
      - name: Build
        id: build
        run: just build
      - name: Install
        id: install
        run: just install
      - name: PulumiUp
        id: up
        run: just test-example-up
      - name: PulumiDown
        id: down
        run: just test-example-down
