name: Makefile

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      actions: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        id: git
        with:
          submodules: "recursive"
          fetch-depth: 0
          fetch-tags: true
      - name: Setup tools
        uses: ./.github/actions/setup-tools
        with:
          tools: go, pulumicli, pulumictl, nodejs, python, dotnet
      - name: Run smoketest container
        run: |
          docker build -t mid-smoketest docker/smoketest/
          docker run -p 2222:22 --name mid-smoketest -d mid-smoketest
      - name: Build
        id: build
        run: |
          make build
      - name: Install
        id: install
        run: |
          set -ex
          make install
      - name: PulumiUp
        id: up
        run: make up
      - name: PulumiDown
        id: down
        run: make down
      - name: Generate multi-language examples from yaml IaC program
        id: examples
        run: |
          set -ex
          make gen_examples
