name: release
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true

permissions:
  contents: write
  packages: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NPM_REGISTRY_URL: https://npm.pkg.github.com
  GOPRIVATE: github.com/sapslaj

jobs:
  build-provider:
    name: build-provider
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goarch:
          - amd64
          - arm64
        goos:
          - linux
          - windows
          - darwin
    steps:
      - uses: actions/checkout@v4
      - name: Setup tools
        uses: ./.github/actions/setup-tools
        with:
          tools: go
      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: "0"
        run: go build -o "./bin/pulumi-resource-mid-${{ inputs.version }}-${{ matrix.goos }}-${{ matrix.goarch }}" -ldflags "-X github.com/sapslaj/mid/provider.Version=$PROVIDER_VERSION" ./provider/cmd/pulumi-resource-mid
      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: pulumi-resource-mid-${{ inputs.version }}-${{ matrix.goos }}-${{ matrix.goarch }}
          path: ./bin/pulumi-resource-mid-${{ inputs.version }}-${{ matrix.goos }}-${{ matrix.goarch }}
          retention-days: 1

  release:
    name: release
    runs-on: ubuntu-latest
    needs: build-provider
    steps:
      - uses: actions/checkout@v4
      - uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Setup tools
        uses: ./.github/actions/setup-tools
        with:
          tools: all
      - name: Build
        run: |
          git config --global url.ssh://git@github.com/.insteadOf https://github.com/
          just provider_version=${{ inputs.version }} build sdk examples
          just tidy
          just fmt
          mkdir dist/
      - name: Commit updates
        id: commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: ${{ inputs.version }}
          tagging_message: ${{ inputs.version }}
          create_branch: false
      - name: Download builds
        uses: actions/download-artifact@v4
        with:
          path: dist/
          pattern: pulumi-resource-mid-*
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.version }}
          fail_on_unmatched_files: true
          files: |
            dist/**/*
          target_commitish: ${{ steps.commit.outputs.commit_hash }}
      - uses: JS-DevTools/npm-publish@v3
        with:
          access: public
          token: ${{ env.NPM_TOKEN }}
          registry: ${{ env.NPM_REGISTRY_URL }}
          package: ${{ github.workspace }}/sdk/nodejs/bin/package.json
